# analysis_options.yaml
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  
  errors:
    missing_required_param: error
    
    missing_return: error
linter:
  rules:
    # Basic lint rules
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_print: false
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true